name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Clean npm cache and install dependencies
        working-directory: frontend
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Build Vite App
        working-directory: frontend
        run: npx vite build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
